/**
 * The single consolidated configuration schema for chart-ts.
 *
 * One object describes data, panes, series, indicators, drawings, axes,
 * crosshair, grid, theme (including Display-P3 colors), watermark, and
 * formatters. There are no scattered option bags.
 *
 * @module
 */

import type { Candle } from './core/data.js';
import {
  DEFAULT_HEATMAP_BUCKET_MS,
  DEFAULT_HEATMAP_COLOR_HIGH,
  DEFAULT_HEATMAP_COLOR_LOW,
  DEFAULT_HEATMAP_GAMMA,
  DEFAULT_HEATMAP_MAX_BUCKETS,
  DEFAULT_HEATMAP_MAX_LEVELS,
  DEFAULT_HEATMAP_MIN_OPACITY,
  DEFAULT_HEATMAP_OPACITY,
  type HeatmapStop,
} from './core/heatmap.js';
import {
  DEFAULT_INLINE_BOOK_ASK_COLOR,
  DEFAULT_INLINE_BOOK_BID_COLOR,
  DEFAULT_INLINE_BOOK_MAX_LEVELS,
  DEFAULT_INLINE_BOOK_WIDTH,
} from './core/inline-book.js';
import type { CanvasImageSourceLike } from './dom.js';

/** Built-in main-series renderers. */
export type SeriesType = 'candlestick' | 'line' | 'area' | 'bar' | 'histogram' | 'heikin-ashi' | 'hollow-candlestick';

/** Main series appearance. Colors accept hex, rgb(a), and `color(display-p3 ...)`. */
export interface SeriesConfig {
  /** A built-in {@link SeriesType}, or a type registered via {@link import('./core/chart.js').Chart.registerSeries}. */
  type: SeriesType | (string & {});
  colorByPreviousClose: boolean;
  bodyVisible: boolean;
  borderVisible: boolean;
  wickVisible: boolean;
  borderUpColor: string;
  borderDownColor: string;
  upColor: string;
  downColor: string;
  /** Wick colors default to the body colors when empty. */
  wickUpColor: string;
  wickDownColor: string;
  /** Line/area series stroke color. */
  lineColor: string;
  lineWidth: number;
  /** Area series fill color (alpha is applied on top). */
  areaFillColor: string;
  areaFillOpacity: number;
  /** Histogram bar color when a candle direction is unavailable. */
  histogramColor: string;
}

/** One indicator instance on the chart. */
export interface IndicatorConfig {
  /** Unique id; generated by {@link import('./core/chart.js').Chart.addIndicator} when omitted. */
  id: string;
  /** Registered indicator name, e.g. `'sma'`, or a custom registered name. */
  name: string;
  /** Parameter overrides merged over the indicator's defaults. */
  params: Record<string, number>;
  /** Draw on the main price pane or in its own sub-pane. */
  pane: 'main' | 'sub';
  /** Line color overrides merged over the indicator's defaults. */
  colors: string[];
  visible: boolean;
  /**
   * Stroke width per output line: indexed like `indicatorLineKeys(def)` when
   * the definition declares style rows (so a width stays with its plot when
   * a study omits some lines), else by output line order. Missing or
   * non-positive entries keep the indicator's own width (1px). Default `[]`.
   */
  lineWidths?: number[];
  /** Keys of output lines, bars, fills or levels to hide. Default `[]`. */
  hiddenLines?: string[];
}

/** A point of a drawing in data coordinates. */
export interface DrawingPoint {
  index: number;
  price: number;
}

/** One drawing instance on the main pane. */
export interface DrawingConfig {
  id: string;
  /** Registered drawing name, e.g. `'trendline'`, or a custom registered name. */
  name: string;
  points: DrawingPoint[];
  color: string;
  lineWidth: number;
  /** Stroke style applied to every line of the drawing. */
  lineStyle: 'solid' | 'dashed' | 'dotted';
  /** Text payload for text-bearing tools (notes, labels, emoji, tables). */
  text: string;
  /** Image payload for the image tool. */
  image: CanvasImageSourceLike | null;
  /** Locked drawings cannot be selected, moved or erased interactively. */
  locked: boolean;
  visible: boolean;
}

/** Text and/or image watermark rendered under the series. */
export interface WatermarkConfig {
  visible: boolean;
  text: string;
  /** Optional image drawn centered under the text; any `drawImage`-able source. */
  image: CanvasImageSourceLike | null;
  color: string;
  /** 0-1; multiplies the color alpha. */
  opacity: number;
  fontSize: number;
  /** Empty string (the default) inherits `theme.fontFamily`. */
  fontFamily: string;
}

/** Price (vertical) axis options. */
export type PriceScaleMode = 'regular' | 'percent' | 'indexed' | 'logarithmic';

export interface PriceAxisConfig {
  visible: boolean;
  /** Minimum width reserved at the selected edge; grows to fit explicit precision. */
  width: number;
  /** Approximate number of ticks. */
  tickCount: number;
  position: 'left' | 'right';
  autoScale: boolean;
  /** Exclude overlay indicators from the main pane's automatic range. */
  scaleSeriesOnly: boolean;
  inverted: boolean;
  mode: PriceScaleMode;
  lockPriceToBarRatio: boolean;
  /** Scale units per bar; null captures the current ratio when locking. */
  priceToBarRatio: number | null;
  /** null preserves the host's price formatter. */
  precision: number | null;
  /** `countdown` adds the bar-close countdown under the last-price badge. */
  labels: { lastPrice: boolean; highLow: boolean; indicator: boolean; countdown: boolean };
  lines: { lastPrice: boolean; previousClose: boolean; highLow: boolean };
  plusButton: boolean;
}

/** Information displayed over the main chart pane. */
export interface StatusLineConfig {
  visible: boolean;
  symbol: string;
  symbolVisible: boolean;
  ohlc: boolean;
  change: boolean;
  volume: boolean;
  indicators: boolean;
  /** Time left until the latest bar closes (needs a known interval, see {@link TimeAxisConfig.intervalMs}). */
  countdown: boolean;
}

/** Time (horizontal) axis options. */
export interface TimeAxisConfig {
  visible: boolean;
  /** Height reserved at the bottom edge for time labels. */
  height: number;
  /** Approximate number of ticks. */
  tickCount: number;
  /**
   * Bar interval in ms for the countdown; null uses {@link TimeScaleConfig.intervalMs}
   * when that is set, else infers it from the last two candles.
   */
  intervalMs: number | null;
}

/**
 * Horizontal scale layout (label options live in {@link TimeAxisConfig}).
 *
 * By default the axis is bar-indexed: every candle takes one bar width and time
 * gaps (weekends, halts, missing candles) collapse, like TradingView and
 * lightweight-charts. That suits 24x7 crypto, but session-based markets then show
 * Friday's close right beside Monday's open. `continuous: true` places each candle
 * at its time slot instead, `round((time - firstTime) * 1000 / intervalMs)`, so gaps
 * appear as empty space; bar spacing, scrolling and zoom are then measured in slots.
 * Drawings, indicators and the {@link import('./core/chart.js').ScaleApi} still use
 * candle indices; indices beyond the data extend one slot per bar.
 */
export interface TimeScaleConfig {
  /** Lay candles out by time so gaps show as empty space. Default false (bar-indexed). */
  continuous: boolean;
  /**
   * Slot width in milliseconds. `null` (default), zero, negative or non-finite values
   * infer it as the most common positive delta between consecutive candle times.
   * The bar-close countdown also uses it when {@link TimeAxisConfig.intervalMs} is null.
   */
  intervalMs: number | null;
}

export interface GridConfig {
  visible: boolean;
  horizontal: boolean;
  vertical: boolean;
  color: string;
}

/** Pointer rendering: full cross, a dot, nothing (plain arrow), or a presenter halo. */
export type CrosshairMode = 'cross' | 'dot' | 'arrow' | 'demonstration';

export interface CrosshairConfig {
  visible: boolean;
  /** How the pointer is drawn; axis label boxes show in every mode except `'arrow'`. */
  mode: CrosshairMode;
  color: string;
  dashed: boolean;
  /** Label box background; an accent color contrasts with both dark and light themes. */
  labelBackground: string;
  /** Label text color; `'auto'` (default) selects black/white by background luminance. */
  labelColor: string;
}

export interface ThemeConfig {
  background: string;
  textColor: string;
  borderColor: string;
  /** Sans family for UI text (and the watermark unless overridden). System fallbacks by default. */
  fontFamily: string;
  /** Monospace/tabular family for the status line and drawing labels; also scale text unless `scaleFontFamily` is set. */
  monoFamily: string;
  /** Status line and drawing label size in CSS pixels; also scale text unless `scaleFontSize` is set. */
  fontSize: number;
  /** Price/time scale text size (ticks, crosshair and price labels); null inherits `fontSize`. */
  scaleFontSize: number | null;
  /** Price/time scale text family; empty string (the default) inherits `monoFamily`. */
  scaleFontFamily: string;
}

/** Volume histogram pinned to the bottom of the main pane, drawn under the series. */
export interface VolumeConfig {
  /** Draw the overlay. Independent of the `vol` sub-pane indicator. */
  overlay: boolean;
  /** Rising-bar color; the `'up'` token (default) follows `series.upColor`. */
  upColor: string;
  /** Falling-bar color; the `'down'` token (default) follows `series.downColor`. */
  downColor: string;
  /** 0-1; multiplies the bar color alpha. */
  opacity: number;
  /** 0-1 fraction of the main pane height reached by the tallest visible bar. */
  height: number;
}

/**
 * Inline order book: a live bid/ask depth ladder docked beside the price
 * axis, fed by `Chart.setDepth` (the datafeed's depth channel). The chart
 * attaches the pane while `enabled` holds and drops it when it clears.
 */
export interface InlineBookConfig {
  /** Dock the inline book pane, sharing the main price scale. */
  enabled: boolean;
  /** Levels shown per side. */
  maxLevels: number;
  /** Bid bar color. */
  bidColor: string;
  /** Ask bar color. */
  askColor: string;
  /** Shade cumulative depth behind the level bars. */
  cumulative: boolean;
  /** Size label per row when the row is tall enough. */
  showLabels: boolean;
  /**
   * `'dock'` gives the book its own strip beside the price axis, shrinking the
   * plot; `'overlay'` paints it behind the series along the plot's right edge,
   * so the plot keeps the full width.
   */
  placement: 'dock' | 'overlay';
  /**
   * `'ladder'` grows every level from the price-axis side; `'mirrored'` grows
   * bids left and asks right from a central column of size labels.
   */
  layout: 'ladder' | 'mirrored';
  /** Book width in CSS pixels: the dock strip, or the overlay band. */
  width: number;
  /** Overlay only: gap in CSS pixels between the band and the price axis. */
  inset: number;
}

/**
 * Liquidity heatmap (Bookmap-style): resting order-book size over time as a
 * color field behind the main series, fed by `Chart.setDepth` (the datafeed's
 * depth channel). While `enabled` holds, the chart retains a bounded window
 * of time-bucketed book snapshots (`maxBuckets` × 2 × `maxLevels` level
 * pairs) and drops it when `enabled` clears.
 */
export interface HeatmapConfig {
  /** Paint the heatmap behind the candles. */
  enabled: boolean;
  /** Wall-clock bucket width in ms; at most one retained snapshot per bucket. */
  bucketMs: number;
  /** Retained buckets (the history window's capacity). */
  maxBuckets: number;
  /** Levels kept per side per snapshot. */
  maxLevels: number;
  /** Ramp color at zero intensity (used when `stops` is empty). */
  colorLow: string;
  /** Ramp color at full intensity (used when `stops` is empty). */
  colorHigh: string;
  /**
   * A custom gradient from zero to full intensity, replacing `colorLow` →
   * `colorHigh` when it has at least one usable color. Bare colors spread
   * evenly; `{ color, at }` pins a stop to an intensity (0-1). A stop's own
   * alpha scales the ramp alpha there. Empty (the default) keeps the two-color ramp.
   */
  stops: HeatmapStop[];
  /** 0-1; peak cell alpha at full intensity. */
  opacity: number;
  /** 0-1; cell alpha at zero intensity, so thin liquidity can stay visible. Default 0. */
  minOpacity: number;
  /** Intensity curve exponent; below 1 lifts small sizes. */
  gamma: number;
}

/** Label formatting hooks. */
export interface FormattersConfig {
  price: (value: number) => string;
  time: (timestamp: number) => string;
}

/**
 * The one consolidated chart configuration schema.
 */
export interface ChartConfig {
  /** Initial candle data. */
  data: Candle[];
  /** Canvas size used when a document (not a container) is injected. */
  width: number;
  height: number;
  /** Enable WASM+SIMD acceleration with automatic JS fallback. */
  wasm: boolean;
  series: SeriesConfig;
  statusLine: StatusLineConfig;
  indicators: IndicatorConfig[];
  drawings: DrawingConfig[];
  priceAxis: PriceAxisConfig;
  timeAxis: TimeAxisConfig;
  /** Bar-indexed (default) or time-continuous horizontal layout. */
  timeScale: TimeScaleConfig;
  grid: GridConfig;
  crosshair: CrosshairConfig;
  theme: ThemeConfig;
  watermark: WatermarkConfig;
  volume: VolumeConfig;
  /** Inline order book docked beside the price axis. */
  inlineBook: InlineBookConfig;
  /** Liquidity heatmap behind the main series. */
  heatmap: HeatmapConfig;
  formatters: FormattersConfig;
  /** Relative height of each indicator sub-pane (main pane weighs 3). */
  indicatorPaneWeight: number;
}

/** Recursive partial used for user-supplied configuration. */
export type DeepPartial<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends readonly (infer U)[]
    ? U[]
    : T extends object
      ? { [K in keyof T]?: DeepPartial<T[K]> }
      : T;

/** Formats a price with a magnitude-appropriate precision. */
export function defaultPriceFormatter(value: number): string {
  const abs = Math.abs(value);
  const digits = abs >= 100 || abs === 0 ? 2 : abs >= 1 ? 4 : 6;
  return value.toFixed(digits);
}

/** Formats a UNIX-second timestamp as `YYYY-MM-DD HH:mm` in UTC. */
export function defaultTimeFormatter(timestamp: number): string {
  const d = new Date(timestamp * 1000);
  const pad = (n: number): string => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}`;
}

/** The factory defaults every config is merged over. */
export const DEFAULT_CONFIG: ChartConfig = {
  data: [],
  width: 800,
  height: 500,
  wasm: true,
  series: {
    type: 'candlestick',
    colorByPreviousClose: false,
    bodyVisible: true,
    borderVisible: false,
    wickVisible: true,
    borderUpColor: '',
    borderDownColor: '',
    upColor: '#26a69a',
    downColor: '#ef5350',
    wickUpColor: '',
    wickDownColor: '',
    lineColor: '#2962ff',
    lineWidth: 2,
    areaFillColor: '#2962ff',
    areaFillOpacity: 0.2,
    histogramColor: '#7e57c2',
  },
  indicators: [],
  drawings: [],
  statusLine: { visible: false, symbol: 'Symbol', symbolVisible: true, ohlc: true, change: true, volume: false, indicators: true, countdown: false },
  priceAxis: {
    visible: true, width: 64, tickCount: 6, position: 'right', autoScale: true,
    scaleSeriesOnly: false, inverted: false, mode: 'regular', lockPriceToBarRatio: false,
    priceToBarRatio: null, precision: null,
    labels: { lastPrice: false, highLow: false, indicator: false, countdown: false },
    lines: { lastPrice: false, previousClose: false, highLow: false }, plusButton: false,
  },
  timeAxis: { visible: true, height: 24, tickCount: 6, intervalMs: null },
  timeScale: { continuous: false, intervalMs: null },
  grid: { visible: true, horizontal: true, vertical: true, color: 'rgba(120, 130, 150, 0.15)' },
  crosshair: { visible: true, mode: 'cross', color: '#758696', dashed: true, labelBackground: '#2962ff', labelColor: 'auto' },
  theme: {
    background: '#ffffff',
    textColor: '#4a5568',
    borderColor: '#e2e8f0',
    fontFamily: 'system-ui, sans-serif',
    monoFamily: 'ui-monospace, monospace',
    fontSize: 12,
    scaleFontSize: null,
    scaleFontFamily: '',
  },
  watermark: {
    visible: false,
    text: '',
    image: null,
    color: '#4a5568',
    opacity: 0.08,
    fontSize: 48,
    fontFamily: '',
  },
  volume: { overlay: false, upColor: 'up', downColor: 'down', opacity: 0.5, height: 0.2 },
  inlineBook: {
    enabled: false,
    maxLevels: DEFAULT_INLINE_BOOK_MAX_LEVELS,
    bidColor: DEFAULT_INLINE_BOOK_BID_COLOR,
    askColor: DEFAULT_INLINE_BOOK_ASK_COLOR,
    cumulative: true,
    showLabels: true,
    placement: 'dock',
    layout: 'ladder',
    width: DEFAULT_INLINE_BOOK_WIDTH,
    inset: 0,
  },
  heatmap: {
    enabled: false,
    bucketMs: DEFAULT_HEATMAP_BUCKET_MS,
    maxBuckets: DEFAULT_HEATMAP_MAX_BUCKETS,
    maxLevels: DEFAULT_HEATMAP_MAX_LEVELS,
    colorLow: DEFAULT_HEATMAP_COLOR_LOW,
    colorHigh: DEFAULT_HEATMAP_COLOR_HIGH,
    stops: [],
    opacity: DEFAULT_HEATMAP_OPACITY,
    minOpacity: DEFAULT_HEATMAP_MIN_OPACITY,
    gamma: DEFAULT_HEATMAP_GAMMA,
  },
  formatters: { price: defaultPriceFormatter, time: defaultTimeFormatter },
  indicatorPaneWeight: 1,
};

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== 'object' || value === null) return false;
  const proto: unknown = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function cloneDeep<T>(value: T): T {
  if (Array.isArray(value)) return value.map(cloneDeep) as T;
  if (isPlainObject(value)) {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value)) out[key] = cloneDeep((value as Record<string, unknown>)[key]);
    return out as T;
  }
  return value;
}

/**
 * Deep-merges `override` over `base`. Plain objects merge recursively;
 * arrays, functions, class instances, and scalars replace. `undefined`
 * values in the override are ignored. Results never alias mutable state
 * (arrays/objects) of either operand.
 */
export function mergeDeep<T>(base: T, override: unknown): T {
  if (override === undefined) return cloneDeep(base);
  if (!isPlainObject(base) || !isPlainObject(override)) {
    return override as T;
  }
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(base)) out[key] = cloneDeep(base[key]);
  for (const key of Object.keys(override)) {
    out[key] = mergeDeep(base[key], override[key]);
  }
  return out as T;
}

/**
 * Merges a user partial over {@link DEFAULT_CONFIG} into a complete config.
 *
 * @param partial - Any subset of the consolidated schema.
 */
export function resolveConfig(partial?: DeepPartial<ChartConfig>): ChartConfig {
  return mergeDeep(DEFAULT_CONFIG, partial ?? {});
}

/**
 * Identity helper that type-checks a config partial. Enables autocompletion
 * in plain JSON-style config files:
 *
 * ```ts
 * export default defineConfig({ series: { type: 'area' }, watermark: { visible: true, text: 'ACME' } });
 * ```
 */
export function defineConfig(partial: DeepPartial<ChartConfig>): DeepPartial<ChartConfig> {
  return partial;
}
