/**
 * The single consolidated configuration schema for chart-ts.
 *
 * One object describes data, panes, series, indicators, drawings, axes,
 * crosshair, grid, theme (including Display-P3 colors), watermark, and
 * formatters. There are no scattered option bags.
 *
 * @module
 */

import type { Candle } from './core/data.js';
import type { CanvasImageSourceLike } from './dom.js';

/** Built-in main-series renderers. */
export type SeriesType = 'candlestick' | 'line' | 'area' | 'bar' | 'histogram';

/** Main series appearance. Colors accept hex, rgb(a), and `color(display-p3 ...)`. */
export interface SeriesConfig {
  type: SeriesType;
  colorByPreviousClose: boolean;
  bodyVisible: boolean;
  borderVisible: boolean;
  wickVisible: boolean;
  borderUpColor: string;
  borderDownColor: string;
  upColor: string;
  downColor: string;
  /** Wick colors default to the body colors when empty. */
  wickUpColor: string;
  wickDownColor: string;
  /** Line/area series stroke color. */
  lineColor: string;
  lineWidth: number;
  /** Area series fill color (alpha is applied on top). */
  areaFillColor: string;
  areaFillOpacity: number;
  /** Histogram bar color when a candle direction is unavailable. */
  histogramColor: string;
}

/** One indicator instance on the chart. */
export interface IndicatorConfig {
  /** Unique id; generated by {@link import('./core/chart.js').Chart.addIndicator} when omitted. */
  id: string;
  /** Registered indicator name, e.g. `'sma'`, or a custom registered name. */
  name: string;
  /** Parameter overrides merged over the indicator's defaults. */
  params: Record<string, number>;
  /** Draw on the main price pane or in its own sub-pane. */
  pane: 'main' | 'sub';
  /** Line color overrides merged over the indicator's defaults. */
  colors: string[];
  visible: boolean;
}

/** A point of a drawing in data coordinates. */
export interface DrawingPoint {
  index: number;
  price: number;
}

/** One drawing instance on the main pane. */
export interface DrawingConfig {
  id: string;
  /** Registered drawing name, e.g. `'trendline'`, or a custom registered name. */
  name: string;
  points: DrawingPoint[];
  color: string;
  lineWidth: number;
  /** Stroke style applied to every line of the drawing. */
  lineStyle: 'solid' | 'dashed' | 'dotted';
  /** Text payload for text-bearing tools (notes, labels, emoji, tables). */
  text: string;
  /** Image payload for the image tool. */
  image: CanvasImageSourceLike | null;
  /** Locked drawings cannot be selected, moved or erased interactively. */
  locked: boolean;
  visible: boolean;
}

/** Text and/or image watermark rendered under the series. */
export interface WatermarkConfig {
  visible: boolean;
  text: string;
  /** Optional image drawn centered under the text; any `drawImage`-able source. */
  image: CanvasImageSourceLike | null;
  color: string;
  /** 0-1; multiplies the color alpha. */
  opacity: number;
  fontSize: number;
  /** Empty string (the default) inherits `theme.fontFamily`. */
  fontFamily: string;
}

/** Price (vertical) axis options. */
export type PriceScaleMode = 'regular' | 'percent' | 'indexed' | 'logarithmic';

export interface PriceAxisConfig {
  visible: boolean;
  /** Minimum width reserved at the selected edge; grows to fit explicit precision. */
  width: number;
  /** Approximate number of ticks. */
  tickCount: number;
  position: 'left' | 'right';
  autoScale: boolean;
  /** Exclude overlay indicators from the main pane's automatic range. */
  scaleSeriesOnly: boolean;
  inverted: boolean;
  mode: PriceScaleMode;
  lockPriceToBarRatio: boolean;
  /** Scale units per bar; null captures the current ratio when locking. */
  priceToBarRatio: number | null;
  /** null preserves the host's price formatter. */
  precision: number | null;
  labels: { lastPrice: boolean; highLow: boolean; indicator: boolean };
  lines: { lastPrice: boolean; previousClose: boolean; highLow: boolean };
  plusButton: boolean;
}

/** Information displayed over the main chart pane. */
export interface StatusLineConfig {
  visible: boolean;
  symbol: string;
  symbolVisible: boolean;
  ohlc: boolean;
  change: boolean;
  volume: boolean;
  indicators: boolean;
}

/** Time (horizontal) axis options. */
export interface TimeAxisConfig {
  visible: boolean;
  /** Height reserved at the bottom edge for time labels. */
  height: number;
  /** Approximate number of ticks. */
  tickCount: number;
}

export interface GridConfig {
  visible: boolean;
  horizontal: boolean;
  vertical: boolean;
  color: string;
}

/** Pointer rendering: full cross, a dot, nothing (plain arrow), or a presenter halo. */
export type CrosshairMode = 'cross' | 'dot' | 'arrow' | 'demonstration';

export interface CrosshairConfig {
  visible: boolean;
  /** How the pointer is drawn; axis label boxes show in every mode except `'arrow'`. */
  mode: CrosshairMode;
  color: string;
  dashed: boolean;
  /** Label box background; an accent color contrasts with both dark and light themes. */
  labelBackground: string;
  /** Label text color; `'auto'` (default) selects black/white by background luminance. */
  labelColor: string;
}

export interface ThemeConfig {
  background: string;
  textColor: string;
  borderColor: string;
  /** Sans family for UI text (and the watermark unless overridden). System fallbacks by default. */
  fontFamily: string;
  /** Monospace/tabular family for numeric text: axis and crosshair labels. */
  monoFamily: string;
  /** Axis and crosshair label size in CSS pixels. */
  fontSize: number;
}

/** Label formatting hooks. */
export interface FormattersConfig {
  price: (value: number) => string;
  time: (timestamp: number) => string;
}

/**
 * The one consolidated chart configuration schema.
 */
export interface ChartConfig {
  /** Initial candle data. */
  data: Candle[];
  /** Canvas size used when a document (not a container) is injected. */
  width: number;
  height: number;
  /** Enable WASM+SIMD acceleration with automatic JS fallback. */
  wasm: boolean;
  series: SeriesConfig;
  statusLine: StatusLineConfig;
  indicators: IndicatorConfig[];
  drawings: DrawingConfig[];
  priceAxis: PriceAxisConfig;
  timeAxis: TimeAxisConfig;
  grid: GridConfig;
  crosshair: CrosshairConfig;
  theme: ThemeConfig;
  watermark: WatermarkConfig;
  formatters: FormattersConfig;
  /** Relative height of each indicator sub-pane (main pane weighs 3). */
  indicatorPaneWeight: number;
}

/** Recursive partial used for user-supplied configuration. */
export type DeepPartial<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends readonly (infer U)[]
    ? U[]
    : T extends object
      ? { [K in keyof T]?: DeepPartial<T[K]> }
      : T;

/** Formats a price with a magnitude-appropriate precision. */
export function defaultPriceFormatter(value: number): string {
  const abs = Math.abs(value);
  const digits = abs >= 100 || abs === 0 ? 2 : abs >= 1 ? 4 : 6;
  return value.toFixed(digits);
}

/** Formats a UNIX-second timestamp as `YYYY-MM-DD HH:mm` in UTC. */
export function defaultTimeFormatter(timestamp: number): string {
  const d = new Date(timestamp * 1000);
  const pad = (n: number): string => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())}`;
}

/** The factory defaults every config is merged over. */
export const DEFAULT_CONFIG: ChartConfig = {
  data: [],
  width: 800,
  height: 500,
  wasm: true,
  series: {
    type: 'candlestick',
    colorByPreviousClose: false,
    bodyVisible: true,
    borderVisible: false,
    wickVisible: true,
    borderUpColor: '',
    borderDownColor: '',
    upColor: '#26a69a',
    downColor: '#ef5350',
    wickUpColor: '',
    wickDownColor: '',
    lineColor: '#2962ff',
    lineWidth: 2,
    areaFillColor: '#2962ff',
    areaFillOpacity: 0.2,
    histogramColor: '#7e57c2',
  },
  indicators: [],
  drawings: [],
  statusLine: { visible: false, symbol: 'Symbol', symbolVisible: true, ohlc: true, change: true, volume: false, indicators: true },
  priceAxis: {
    visible: true, width: 64, tickCount: 6, position: 'right', autoScale: true,
    scaleSeriesOnly: false, inverted: false, mode: 'regular', lockPriceToBarRatio: false,
    priceToBarRatio: null, precision: null,
    labels: { lastPrice: false, highLow: false, indicator: false },
    lines: { lastPrice: false, previousClose: false, highLow: false }, plusButton: false,
  },
  timeAxis: { visible: true, height: 24, tickCount: 6 },
  grid: { visible: true, horizontal: true, vertical: true, color: 'rgba(120, 130, 150, 0.15)' },
  crosshair: { visible: true, mode: 'cross', color: '#758696', dashed: true, labelBackground: '#2962ff', labelColor: 'auto' },
  theme: {
    background: '#ffffff',
    textColor: '#4a5568',
    borderColor: '#e2e8f0',
    fontFamily: 'system-ui, sans-serif',
    monoFamily: 'ui-monospace, monospace',
    fontSize: 12,
  },
  watermark: {
    visible: false,
    text: '',
    image: null,
    color: '#4a5568',
    opacity: 0.08,
    fontSize: 48,
    fontFamily: '',
  },
  formatters: { price: defaultPriceFormatter, time: defaultTimeFormatter },
  indicatorPaneWeight: 1,
};

function isPlainObject(value: unknown): value is Record<string, unknown> {
  if (typeof value !== 'object' || value === null) return false;
  const proto: unknown = Object.getPrototypeOf(value);
  return proto === Object.prototype || proto === null;
}

function cloneDeep<T>(value: T): T {
  if (Array.isArray(value)) return value.map(cloneDeep) as T;
  if (isPlainObject(value)) {
    const out: Record<string, unknown> = {};
    for (const key of Object.keys(value)) out[key] = cloneDeep((value as Record<string, unknown>)[key]);
    return out as T;
  }
  return value;
}

/**
 * Deep-merges `override` over `base`. Plain objects merge recursively;
 * arrays, functions, class instances, and scalars replace. `undefined`
 * values in the override are ignored. Results never alias mutable state
 * (arrays/objects) of either operand.
 */
export function mergeDeep<T>(base: T, override: unknown): T {
  if (override === undefined) return cloneDeep(base);
  if (!isPlainObject(base) || !isPlainObject(override)) {
    return override as T;
  }
  const out: Record<string, unknown> = {};
  for (const key of Object.keys(base)) out[key] = cloneDeep(base[key]);
  for (const key of Object.keys(override)) {
    out[key] = mergeDeep(base[key], override[key]);
  }
  return out as T;
}

/**
 * Merges a user partial over {@link DEFAULT_CONFIG} into a complete config.
 *
 * @param partial - Any subset of the consolidated schema.
 */
export function resolveConfig(partial?: DeepPartial<ChartConfig>): ChartConfig {
  return mergeDeep(DEFAULT_CONFIG, partial ?? {});
}

/**
 * Identity helper that type-checks a config partial. Enables autocompletion
 * in plain JSON-style config files:
 *
 * ```ts
 * export default defineConfig({ series: { type: 'area' }, watermark: { visible: true, text: 'ACME' } });
 * ```
 */
export function defineConfig(partial: DeepPartial<ChartConfig>): DeepPartial<ChartConfig> {
  return partial;
}
