/**
 * Generates icons.js from the hand-authored Lucide-style SVGs in this
 * directory. The .svg files are the source of truth; run
 * `node demo/icons/build-icons.mjs` after editing them.
 *
 * Validation: every file must be a single-root <svg> with balanced tags and
 * carry the Lucide baseline attributes.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

const REQUIRED_ATTRS = [
  'viewBox="0 0 24 24"',
  'fill="none"',
  'stroke="currentColor"',
  'stroke-width="2"',
  'stroke-linecap="round"',
  'stroke-linejoin="round"',
];

function validate(name, svg) {
  for (const attr of REQUIRED_ATTRS) {
    if (!svg.includes(attr)) throw new Error(`${name}: missing ${attr}`);
  }
  // Lightweight well-formedness: every opened tag is self-closed or closed.
  const tags = svg.match(/<[^>]+>/g) ?? [];
  const stack = [];
  for (const tag of tags) {
    if (tag.startsWith('</')) {
      const closing = tag.slice(2, -1);
      if (stack.pop() !== closing) throw new Error(`${name}: unbalanced tag ${tag}`);
    } else if (!tag.endsWith('/>')) {
      stack.push(tag.slice(1).split(/[\s>]/)[0]);
    }
  }
  if (stack.length !== 0) throw new Error(`${name}: unclosed tags ${stack.join(', ')}`);
  if (!svg.startsWith('<svg ') || !svg.endsWith('</svg>')) {
    throw new Error(`${name}: expected a single root <svg>`);
  }
}

const files = readdirSync(here)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const entries = [];
for (const file of files) {
  const svg = readFileSync(join(here, file), 'utf8').trim().replace(/\s*\n\s*/g, '');
  validate(file, svg);
  entries.push(`  ${JSON.stringify(file.replace(/\.svg$/, ''))}: ${JSON.stringify(svg)},`);
}

const out = `// GENERATED by demo/icons/build-icons.mjs from the .svg files in this directory.
// Do not edit by hand; edit the SVGs and re-run the generator.

/** Icon name → verbatim SVG markup (Lucide-style: 24×24, stroke=currentColor). */
export const ICONS = {
${entries.join('\n')}
};

/**
 * Returns the SVG markup for \`name\` with width/height set.
 * Unknown names return an empty string.
 */
export function icon(name, size = 20) {
  const svg = ICONS[name];
  if (svg === undefined) return '';
  return svg.replace('<svg ', \`<svg width="\${size}" height="\${size}" \`);
}
`;

writeFileSync(join(here, 'icons.js'), out);
console.log(`icons.js regenerated: ${files.length} icons (${files.join(', ')})`);
