/**
 * Generates src/ui/icons.ts from the hand-authored Lucide-style SVGs in
 * assets/icons. The .svg files are the source of truth; run
 * `npm run build:icons` after editing them.
 *
 * Validation: every file must be a single-root <svg> with balanced tags and
 * carry the Lucide baseline attributes.
 */
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const here = join(root, 'assets', 'icons');

const REQUIRED_ATTRS = [
  'viewBox="0 0 24 24"',
  'fill="none"',
  'stroke="currentColor"',
  'stroke-width="1.5"',
  'stroke-linecap="round"',
  'stroke-linejoin="round"',
];

function validate(name, svg) {
  for (const attr of REQUIRED_ATTRS) {
    if (!svg.includes(attr)) throw new Error(`${name}: missing ${attr}`);
  }
  // Lightweight well-formedness: every opened tag is self-closed or closed.
  const tags = svg.match(/<[^>]+>/g) ?? [];
  const stack = [];
  for (const tag of tags) {
    if (tag.startsWith('</')) {
      const closing = tag.slice(2, -1);
      if (stack.pop() !== closing) throw new Error(`${name}: unbalanced tag ${tag}`);
    } else if (!tag.endsWith('/>')) {
      stack.push(tag.slice(1).split(/[\s>]/)[0]);
    }
  }
  if (stack.length !== 0) throw new Error(`${name}: unclosed tags ${stack.join(', ')}`);
  if (!svg.startsWith('<svg ') || !svg.endsWith('</svg>')) {
    throw new Error(`${name}: expected a single root <svg>`);
  }
}

const files = readdirSync(here)
  .filter((f) => f.endsWith('.svg'))
  .sort();

const entries = [];
for (const file of files) {
  const svg = readFileSync(join(here, file), 'utf8').trim().replace(/\s*\n\s*/g, '');
  validate(file, svg);
  entries.push(`  ${JSON.stringify(file.replace(/\.svg$/, ''))}: ${JSON.stringify(svg)},`);
}

const out = `// GENERATED by scripts/build-icons.mjs from assets/icons/*.svg.
// Do not edit by hand; edit the SVGs and run \`npm run build:icons\`.

/**
 * Toolbar icon set: icon name → SVG markup (24×24 Lucide-style, 1.5px
 * stroke in \`currentColor\`). Drawing-tool icons are keyed by the tool's
 * registry name.
 *
 * @module
 */

/** Icon name → verbatim SVG markup. */
export const ICONS: Readonly<Record<string, string>> = {
${entries.join('\n')}
};

/** Returns the SVG markup for \`name\` at \`size\` px, or \`''\` for unknown names. */
export function icon(name: string, size = 20): string {
  const svg = ICONS[name];
  if (svg === undefined) return '';
  return svg.replace('<svg ', \`<svg width="\${size}" height="\${size}" aria-hidden="true" \`);
}
`;

writeFileSync(join(root, 'src', 'ui', 'icons.ts'), out);
console.log(`src/ui/icons.ts regenerated: ${files.length} icons (${files.join(', ')})`);
