/**
 * Compiles src/wasm/kernels.wat to wasm, validates it (including SIMD
 * encodings), and writes the embedded base64 module to
 * src/wasm/kernels.base64.ts. The generated file IS committed so library
 * consumers need no toolchain.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import wabt from 'wabt';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const watPath = join(root, 'src', 'wasm', 'kernels.wat');
const outPath = join(root, 'src', 'wasm', 'kernels.base64.ts');

const wat = readFileSync(watPath, 'utf8');
const w = await wabt();
const mod = w.parseWat(watPath, wat, { simd: true, multiValue: true });
const { buffer, log } = mod.toBinary({ write_debug_names: false });
if (log) process.stderr.write(log);
mod.destroy();

// Sanity check: the bytes must compile in the current engine (SIMD included).
await WebAssembly.compile(buffer);

const base64 = Buffer.from(buffer).toString('base64');
const banner = `// GENERATED by scripts/build-wasm.mjs from src/wasm/kernels.wat. Do not edit.
// Regenerate with: npm run build:wasm
`;
const body = `/** Base64-encoded WASM module with SIMD math kernels. */\nexport const KERNELS_BASE64 = '${base64}';\n`;
writeFileSync(outPath, banner + body);
console.log(`wrote ${outPath} (${buffer.byteLength} bytes wasm, ${base64.length} chars base64)`);
